### ISSUE TITLE
[Android Bootcamp] Group Project: Train Together - Implementation (Sprint 1) - Ready for Review

### ISSUE THREAD

**Issue by ameya-pandilwar** [traintogether/traintogether#14]
Our implementations for the first sprint of the app are complete, please review. /cc @codepathreview @codepath

The walkthroughs are available at -
https://github.com/traintogether/traintogether#walkthroughs-sprint-1

**Comment by codepathreview** [comment]
:+1: Nice work creating tasks for sprint 1. The goal of this sprint is to have the basic screens and workflows ready as much as possible. A few notes
- Stories are well defined and seem achievable in the given time-frame. Consider dividing these stories into even smaller tasks.
- Good work dividing tasks among team members. This is critical in working as a team and also gives equal learning opportunity to everyone involved
- Good to see everyone [contributing](https://github.com/traintogether/traintogether/graphs/contributors) to the project.
- Nice to see that you created milestones for the sprints.
- Depending on the strategy your group has come up with, consider creating regular pull requests to sync up your code to avoid having multiple merge conflicts at the end.
- Consider creating tasks to QA the app a few times to check the basic flow. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.

Consider incorporating as many screens as possible in this sprint so you can have enough time to add UI polish and advanced features later on. It is those little extra things you do that make everything feel more polished and desirable to use. Look forward to what you all come up with.
